[package]
name = "voxelite"
version = "0.0.1"
authors = ["Akshay Trivedi"]
edition = "2018"

[dependencies]
winit = "0.25.0"
erupt = "0.19.0"

log = "0.4.14"
env_logger = "0.8.3"

ultraviolet = "0.8.1"

[build-dependencies]
glsl = { version = "6.0.0", features = ["spirv"] }
