[package]
name = "voxelite"
version = "0.0.1"
authors = ["Akshay Trivedi"]
edition = "2018"

[dependencies]
winit = "0.25.0"
erupt = { git = "https://gitlab.com/Friz64/erupt", branch = "main" }

log = "0.4.14"
env_logger = "0.8.3"

ultraviolet = "0.8.1"
vk-shader-macros = "0.2.7"